[project]
name = "infra_10x_i"
version = "0.0.2"
authors = [
    { name = "Sasha Davidovich", email = "sasha.davidovich@pevzner.com" },
    { name = "Ilya Pevzner", email = "ilya.pevzner@pevzner.com" }
]
description = "10X Universe Infrastructure Internals"
requires-python='>=3.11'

[project.optional-dependencies]
test = ["pytest"]

[build-system]
requires = [
    "scikit-build-core>=0.10.7",
]
build-backend = "scikit_build_core.build"

[tool.cibuildwheel]
test-command = "python {project}/tests/test.py"

[tool.ruff]
target-version = "py37"

[tool.ruff.lint]
extend-select = [
  "B",   # flake8-bugbear
  "I",   # isort
  "PGH", # pygrep-hooks
  "RUF", # Ruff-specific
  "UP",  # pyupgrade
]
