[project]
name = "core_10x_i"
version = "0.1.1"
authors = [
    { name = "Sasha Davidovich", email = "founders@10x-software.org" },
    { name = "Ilya Pevzner", email = "founders@10x-software.org" }
]
description = "10X Universe Core Internals"
requires-python='>=3.10'

[project.optional-dependencies]
test = ["pytest", ]

[build-system]
requires = [
    "scikit-build-core>=0.10.7",
]
build-backend = "scikit_build_core.build"

[tool.cibuildwheel]
test-command = "python {project}/tests/test.py"

[tool.ruff]
target-version = "py37"

[tool.ruff.lint]
extend-select = [
  "B",   # flake8-bugbear
  "I",   # isort
  "PGH", # pygrep-hooks
  "RUF", # Ruff-specific
  "UP",  # pyupgrade
]
